// auth
export const LOGIN_FAILED = "LOGIN_FAILED";
export const LOGIN_LOADING = "LOGIN_LOADING";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const REGISTER_FAILED = "REGISTER_FAILED";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";

// course
export const SET_COURSE_LOADING = "SET_COURSE_LOADING";
export const COURSE_GET_ALL = "COURSE_GET_ALL";
export const COURSE_GET_ALL_FAILED = "COURSE_GET_ALL_FAILED";

export const COURSE_GET_BY_ID = "COURSE_GET_BY_ID";
export const COURSE_GET_BY_ID_FAILED = "COURSE_GET_BY_ID_FAILED";

export const COURSE_ADD = "COURSE_ADD";
export const COURSE_ADD_FAILED = "COURSE_ADD_FAILED";

export const COURSE_REMOVE = "COURSE_REMOVE";
export const COURSE_REMOVE_FAILED = "COURSE_REMOVE_FAILED";

// exam
export const SET_EXAM_LOADING = "SET_EXAM_LOADING";
export const EXAM_GET_ALL = "EXAM_GET_ALL";
export const EXAM_GET_ALL_FAILED = "EXAM_GET_ALL_FAILED";

export const EXAM_GET_BY_ID = "EXAM_GET_BY_ID";
export const EXAM_GET_BY_ID_FAILED = "EXAM_GET_BY_ID_FAILED";

export const EXAM_ADD = "EXAM_ADD";
export const EXAM_ADD_FAILED = "EXAM_ADD_FAILED";

export const EXAM_REMOVE = "EXAM_REMOVE";
export const EXAM_REMOVE_FAILED = "EXAM_REMOVE_FAILED";

// question
export const SET_QUESTION_LOADING = "SET_QUESTION_LOADING";
export const QUESTION_GET_ALL = "QUESTION_GET_ALL";
export const QUESTION_GET_ALL_FAILED = "QUESTION_GET_ALL_FAILED";

export const QUESTION_ADD_NEW = "QUESTION_ADD_NEW";
export const QUESTION_ADD_NEW_FAILED = "QUESTION_ADD_NEW_FAILED";

export const QUESTION_REMOVE = "QUESTION_REMOVE";
export const QUESTION_REMOVE_FAILED = "QUESTION_REMOVE_FAILED";

export const QUESITON_UPDATE = "QUESITON_UPDATE";
export const QUESITON_UPDATE_FAILED = "QUESITON_UPDATE_FAILED";
export const QUESITON_UPDATE_SUCCESS = "QUESITON_UPDATE_SUCCESS"

//category
export const SET_CATEGORY_LOADING = "SET_CATEGORY_LOADING";
export const CATEGORY_GET_ALL = "CATEGORY_GET_ALL";
export const CATEGORY_GET_ALL_FAILED = "CATEGORY_GET_ALL_FAILED";

// result
export const SET_RESULT_LOADING = "SET_RESULT_LOADING";
export const RESULT_GET_ALL = "RESULT_GET_ALL";
export const RESULT_GAT_ALL_FAILED = "RESULT_GAT_ALL_FAILED";
export const RESULT_ADD_NEW = "RESULT_ADD_NEW";
export const RESULT_ADD_NEW_FAILED = "RESULT_ADD_NEW_FAILED";
