// auth
export const LOGIN_FAILED = "LOGIN_FAILED";
export const LOGIN_LOADING = "LOGIN_LOADING";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const REGISTER_FAILED = "REGISTER_FAILED";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";

// course
export const SET_COURSE_LOADING = "SET_COURSE_LOADING";
export const COURSE_GET_ALL = "COURSE_GET_ALL";
export const COURSE_GET_ALL_FAILED = "COURSE_GET_ALL_FAILED";

export const COURSE_GET_BY_ID = "COURSE_GET_BY_ID";
export const COURSE_GET_BY_ID_FAILED = "COURSE_GET_BY_ID_FAILED";

export const COURSE_ADD = "COURSE_ADD";
export const COURSE_ADD_FAILED = "COURSE_ADD_FAILED";

export const COURSE_REMOVE = "COURSE_REMOVE";
export const COURSE_REMOVE_FAILED = "COURSE_REMOVE_FAILED";

// exam
export const SET_EXAM_LOADING = "SET_EXAM_LOADING";
export const EXAM_GET_ALL = "EXAM_GET_ALL";
export const EXAM_GET_ALL_FAILED = "EXAM_GET_ALL_FAILED";

export const EXAM_GET_BY_ID = "EXAM_GET_BY_ID";
export const EXAM_GET_BY_ID_FAILED = "EXAM_GET_BY_ID_FAILED";

export const EXAM_ADD = "EXAM_ADD";
export const EXAM_ADD_FAILED = "EXAM_ADD_FAILED";

export const EXAM_REMOVE = "EXAM_REMOVE";
export const EXAM_REMOVE_FAILED = "EXAM_REMOVE_FAILED";

export const UPDATE_EXAM = "UPDATE_EXAM";
export const UPDATE_EXAM_FAILED = "UPDATE_EXAM_FAILED";

// question
export const SET_QUESTION_LOADING = "SET_QUESTION_LOADING";
export const QUESTION_GET_ALL = "QUESTION_GET_ALL";
export const QUESTION_GET_ALL_FAILED = "QUESTION_GET_ALL_FAILED";

export const QUESTION_ADD_NEW = "QUESTION_ADD_NEW";
export const QUESTION_ADD_NEW_FAILED = "QUESTION_ADD_NEW_FAILED";

export const QUESTION_REMOVE = "QUESTION_REMOVE";
export const QUESTION_REMOVE_FAILED = "QUESTION_REMOVE_FAILED";

export const QUESITON_UPDATE = "QUESITON_UPDATE";
export const QUESITON_UPDATE_FAILED = "QUESITON_UPDATE_FAILED";
export const QUESITON_UPDATE_SUCCESS = "QUESITON_UPDATE_SUCCESS";

//category
export const SET_CATEGORY_LOADING = "SET_CATEGORY_LOADING";
export const CATEGORY_GET_ALL = "CATEGORY_GET_ALL";
export const CATEGORY_GET_ALL_FAILED = "CATEGORY_GET_ALL_FAILED";
export const DELETE_CATEGORY = "DELETE_CATEGORY";
export const DELETE_CATEGORY_FAILED = "DELETE_CATEGORY_FAILED";
export const CREATE_CATEGORY = "CREATE_CATEGORY";
export const CREATE_CATEGORY_FAILED = "CREATE_CATEGORY_FAILED";
export const UPDATE_CATEGORY = "UPDATE_CATEGORY";
export const UPDATE_CATEGORY_FAILED = "UPDATE_CATEGORY_FAILED";

// result
export const SET_RESULT_LOADING = "SET_RESULT_LOADING";
export const RESULT_GET_ALL = "RESULT_GET_ALL";
export const RESULT_GAT_ALL_FAILED = "RESULT_GAT_ALL_FAILED";
export const RESULT_ADD_NEW = "RESULT_ADD_NEW";
export const RESULT_ADD_NEW_FAILED = "RESULT_ADD_NEW_FAILED";

//user
export const GET_ALL_USER = "GET_ALL_USER";
export const GET_ALL_USER_FALIED = "GET_ALL_USER_FALIED";
export const SET_USER_LOADING = "SET_USER_LOADING";
export const UPDATE_USER = "UPDATE_USER";
export const UPDATE_USER_FAILED = "UPDATE_USER_FAILED";
export const DELETE_USER = "DELETE_USER";
export const DELETE_USER_FAILED = "DELETE_USER_FAILED";

//class
export const GET_CLASS = "GET_CLASS";
export const GET_CLASS_FAILED = "GET_CLASS_FAILED";
export const UPDATE_CLASS = "UPDATE_CLASS";
export const UPDATE_CLASS_FAIELD = "UPDATE_CLASS_FAIELD";
export const SET_CLASS_LOADING = "SET_CLASS_LOADING";
export const ADD_CLASS = "ADD_CLASS";
export const ADD_CLASS_FAILED = "ADD_CLASS_FAILED";
export const DELETE_CLASS = "DELETE_CLASS";
export const DELETE_CLASS_SUCCESS = "DELETE_CLASS_SUCCESS";
